# Generated by Django 6.0.6 on 2026-08-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bad_action',
            name='nombre',
            field=models.IntegerField(default=0, verbose_name='Nombre de fois commis'),
        ),
        migrations.AddField(
            model_name='session_activite',
            name='pc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du pc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
