# Generated by Django 6.0.6 on 2026-08-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_bad_action_nombre_session_activite_pc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='justification',
            field=models.TextField(blank=True, null=True, verbose_name='Justification IA'),
        ),
    ]
