# Generated by Django 6.0.6 on 2026-08-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='bad_action',
            name='titre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre'),
        ),
    ]
