# Generated by Django 6.0.6 on 2026-08-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_application_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Vérifiée'),
        ),
    ]
