# Generated by Django 6.0.6 on 2026-07-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='heure_fin',
            field=models.TimeField(auto_now_add=True, verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='session_activite',
            name='heure_fin',
            field=models.TimeField(auto_now_add=True, verbose_name='Heure de fin'),
        ),
    ]
