# Generated by Django 6.0.6 on 2026-07-29 12:29

import compte.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='heure_debut',
            field=models.TimeField(default=compte.models.heure_actuelle, verbose_name='Heure de debut'),
        ),
        migrations.AlterField(
            model_name='session_activite',
            name='heure_debut',
            field=models.TimeField(default=compte.models.heure_actuelle, verbose_name='Heure de debut'),
        ),
        migrations.AlterField(
            model_name='session_activite',
            name='jour',
            field=models.DateField(default=compte.models.heure_actuelle, verbose_name='Jour'),
        ),
    ]
