# Generated by Django 6.0.6 on 2026-07-29 12:31

import compte.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_alter_application_heure_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_activite',
            name='jour',
            field=models.DateField(default=compte.models.jour_actuelle, verbose_name='Jour'),
        ),
    ]
